[project]
name = "dailymail_uk_headlines"
version = "0.1.0"
description = "Add a short description here"
authors = ["Lode Nachtergaele <lode.nachtergaele@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-64", "linux-64"]

[tasks]

[dependencies]
beautifulsoup4 = ">=4.12.3,<4.13"
requests = ">=2.31.0,<2.32"
